apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ffqby3tnu-nodejs-gitops
  description: This is GitOps manifest for ffqby3tnu-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=ffqby3tnu-nodejs
    backstage.io/kubernetes-id: ffqby3tnu-nodejs 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: ffqby3tnu-nodejs   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:ffqby3tnu-nodejs
