apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ffqby3tnu-nodejs
  janus-idp.io/tekton: ffqby3tnu-nodejs
  backstage.io/kubernetes-id: ffqby3tnu-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ffqby3tnu-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
