apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: ffqby3tnu-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ffqby3tnu-nodejs 
  name: ffqby3tnu-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: ffqby3tnu-nodejs 
